name: euro-calliope
channels:
    - conda-forge
    - bioconda
dependencies:
    - python=3.11
    - pycountry=18.12.8
    - snakemake-minimal=8.10.7
variables:
    SNAKEMAKE_PROFILE: ./profiles/default
