name: euro-calliope
channels:
    - conda-forge
    - bioconda
dependencies:
    - python=3.11
    - pycountry=18.12.8
    - snakemake-minimal=7.26.0
variables:
    SNAKEMAKE_PROFILE: ./profiles/default
