__default__:
    runtime: 10
    cores: 1
    memory: 16000
    output: "build/logs/{rule}.{wildcards}.log"
    name: "{rule}.{wildcards}"
test:
    runtime: 240
    cores: 1
    memory: 16000
download_runoff_data:
    runtime: 240
