name: euro-calliope
channels:
    - conda-forge
    - gurobi
dependencies:
    - python=3.9
    - numpy=1.23
    - pandas=1.5
    - xarray=2022.3
    - netCDF4=1.6.2
    - hdf5=1.12.2
    - libnetcdf=4.8.1
    - gurobi=9.5.1
    - calliope=0.6.10
    - pyomo=6.4.1
